export const softSkills = [
  "Comunicação eficaz",
  "Trabalho em equipe",
  "Resolução de problemas",
  "Criatividade",
  "Empatia",
  "Inteligência emocional",
  "Flexibilidade",
  "Capacidade de adaptação",
  "Gestão de tempo",
  "Pensamento crítico",
  "Proatividade",
  "Atenção aos detalhes",
  "Autogestão",
  "Liderança",
  "Habilidades de negociação",
  "Persuasão",
  "Escuta ativa",
  "Capacidade de colaboração",
  "Resiliência",
  "Gestão de conflitos",
  "Capacidade de aprendizado contínuo",
  "Motivação",
  "Tomada de decisão",
  "Organização",
  "Habilidades interpessoais",
  "Habilidades de networking",
  "Senso de responsabilidade",
  "Mentoria",
  "Capacidade de influenciar",
  "Ética profissional",
  "Iniciativa",
  "Capacidade de delegar",
  "Versatilidade",
  "Empoderamento",
  "Adaptabilidade cultural",
  "Resolução de problemas complexos",
  "Gerenciamento de stress",
  "Inovação",
  "Autoconfiança",
  "Autocontrole",
  "Capacidade de autoavaliação",
  "Capacidade de planejamento",
  "Capacidade de priorização",
  "Habilidades de relacionamento interpessoal",
  "Tolerância a diferentes opiniões",
  "Habilidades de facilitação",
  "Colaboração interdepartamental",
  "Habilidades de escuta",
  "Habilidades de análise",
  "Capacidade de síntese",
  "Tomada de decisões sob pressão",
  "Atitude positiva",
  "Curiosidade",
  "Abordagem construtiva",
  "Mentalidade de crescimento",
  "Confiabilidade",
  "Capacidade de liderança situacional",
  "Comprometimento",
  "Capacidade de mediação",
  "Visão estratégica",
  "Habilidades de coaching",
  "Capacidade de automotivação",
  "Gestão de relacionamentos",
  "Capacidade de observação",
  "Capacidade de adaptação ao digital",
  "Pensamento sistêmico",
  "Habilidades de colaboração remota",
  "Negociação de conflitos",
  "Habilidades de relacionamento multicultural",
  "Capacidade de fornecer e receber feedback",
  "Empreendedorismo",
  "Habilidades de comunicação não-verbal",
  "Capacidade de lidar com mudanças"
];
